name: Build and validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable --no-self-update && rustup default stable
      - name: Use rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Build and test
        run: cargo test --all
